<?php

/**
 * @file
 * Code for the Stanford SOE R25 module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_soe_r25_form_stanford_r25_reservation_alter(&$form, &$form_state, $form_id) {
  // We need to alter the reservation form and add field settings.
  // The settings for "Event Attributes" 191,183,178,198,141, and 166.
  $form['stanford_r25_booking_tentative']['#weight'] = -11;
  $form['stanford_r25_booking_date']['#weight'] = -10;
  $form['stanford_r25_booking_duration']['#weight'] = -9;
  $form['stanford_r25_booking_enddate']['#weight'] = -8;
  $form['stanford_r25_booking_reason']['#weight'] = -7;
  $form['stanford_r25_booking_attr191']['#weight'] = -3;
  $form['stanford_r25_booking_headcount']['#weight'] = -2;
  $form['stanford_r25_booking_attr183']['#weight'] = -1;
  $form['stanford_r25_booking_reason']['#title'] = t('Event Title');
  $form['stanford_r25_booking_attr182']['#title'] = t('Event Details');
  $form['stanford_r25_booking_attr191']['#title'] = t('Primary Organization');
  $form['stanford_r25_booking_attr201']['#type'] = 'radios';
  $form['stanford_r25_booking_attr201']['#options'] = array(1 => t('Yes'), 0 => t('No'));
  $form['stanford_r25_booking_attr201']['#default_value'] = variable_get('stanford_r25_booking_attr201', 0);
  $form['stanford_r25_booking_attr200']['#type'] = 'radios';
  $form['stanford_r25_booking_attr200']['#options'] = array(1 => t('Yes'), 0 => t('No'));
  $form['stanford_r25_booking_attr200']['#default_value'] = variable_get('stanford_r25_booking_attr200', 0);
  $form['stanford_r25_booking_attr178']['#suffix'] = '<div class="form-item"><span class="description">' . t('If unsure, please put N/A') . '</span></div>';
  $form['submit']['#prefix'] = '<div class="form-item"><span class="readandagree">' . t('By clicking the Request button, I confirm that I have read and agree to the') . ' ' . l(t("Booking Agreement"), 'https://insidesoe.stanford.edu/science-and-engineering-quad/policies-rates') . '.</span></div>';
  $form['stanford_r25_booking_attr183']['#suffix'] = '<div class="form-item"><span class="description">' . t('E.g., 1234567-123-ABCDE (Case sensitive)') . '</span></div>';
  $form['stanford_r25_booking_attr199']['#suffix'] = '<div class="form-item"><span class="description">' . t('E.g. Reservation spans multiple days; Breakout spaces needed') . '</span></div>';
  $form['stanford_r25_booking_date']['#suffix'] = '<div class="starttime">' . t('Start time includes set-up time') . '</div>';
  $form['stanford_r25_booking_enddate']['#suffix'] = '<div class="endtime">' . t('End time includes break-down time') . '</div>';
  $form['stanford_r25_booking_attr182']['#maxlength'] = 80;

  // We need this to be first for the verification to happen
  // before the room booking takes place.
  array_unshift($form['#validate'], 'stanford_soe_r25_stanford_r25_pta_validate');
}

/**
 * We need to validate the PTA Number.
 *
 * - Throw a validation error message if the ";" character is entered
 *   in the stanford_r25_booking_reason field.
 * - Throw a validation error message if the PTA field (attr 183 in 25 Live)
 *   if the value entered doesn't qualify as a valid PTA number format.
 *
 * @param array $form
 *   The form to update.
 * @param array $form_state
 *   Submitted form state.
 */
function stanford_soe_r25_stanford_r25_pta_validate($form, &$form_state) {
  $booking_reason_value = $form_state['values']['stanford_r25_booking_reason'];
  if (preg_match('/;/', $booking_reason_value)) {
    form_set_error('stanford_r25_booking_reason', t('Please do not include the ; character in the title of the event.'));
  }

  $pta_value = trim($form_state['values']['stanford_r25_booking_attr183']);
  if (!(preg_match('/^(\d{7})\-(\d.*)\-([A-Z]{5})$/', $pta_value))) {
    form_set_error('stanford_r25_booking_attr183', t('Invalid PTA Format. The correct format is Project-Task-Award (e.g. 1234567-123-ABCDE)'));
  }
}
