<?php

function tt_form_stanford_soe_r25_reservation_alter(&$form, &$form_state, $form_id) {
  $form['stanford_soe_r25_booking_tentative']['#weight'] = -11;
  $form['stanford_soe_r25_booking_date']['#weight'] = -10;
  $form['stanford_soe_r25_booking_duration']['#weight'] = -9;
  $form['stanford_soe_r25_booking_enddate']['#weight'] = -8;
  $form['stanford_soe_r25_booking_reason']['#weight'] = -7;
  $form['stanford_soe_r25_booking_attr191']['#weight'] = -3;
  $form['stanford_soe_r25_booking_headcount']['#weight'] = -2;
  $form['stanford_soe_r25_booking_attr144']['#weight'] = -1;
  $form['stanford_soe_r25_booking_reason']['#title'] = 'Event Title';
  $form['stanford_soe_r25_booking_attr182']['#title'] = 'Event Details';
  //$form['stanford_soe_r25_booking_headcount']['#type'] = 'hidden';
  //$form['stanford_soe_r25_booking_headcount']['#value'] = 1;
  $form['submit']['#prefix'] = '<span>By clicking the Reserve button, I confirm that I have read and agree to the <a href="https://insidesoe.stanford.edu/science-and-engineering-quad/policies-rates">Facility Rental Policy</a></span><br />';
  $form['stanford_soe_r25_booking_attr144']['#suffix'] = '<div class="form-item"><span class="description">E.g., 1234567-123-ABCDE (Case sensitive)</span></div>';
  $form['stanford_soe_r25_booking_attr182']['#suffix'] = '<div class="form-item"><span class="description">E.g.<br> - Reservation spans muiltiple days<br>- Breakout spaces needed</span></div>';
  $form['stanford_soe_r25_booking_attr182']['#maxlength'] = 80;
  array_unshift($form['#validate'], 'tt_stanford_soe_r25_pta_validate');
}

// Remove the Headcount: 2 (which is hard-coded) from the tool tip
function tt_stanford_soe_r25_contact_alter(&$data) {
  $data = str_replace('<br />Headcount: 2', '', $data);
  $data = str_replace('<br />Headcount:', '', $data);
}

function tt_stanford_soe_r25_pta_validate($form, &$form_state) {
  if (preg_match('/;/', $form_state['values']['stanford_soe_r25_booking_reason'])) {
      form_set_error('stanford_soe_r25_booking_reason', t('Please do not include the ; character in the title of the event.'));
  }

  $form_state['values']['stanford_soe_r25_booking_attr144'] = trim($form_state['values']['stanford_soe_r25_booking_attr144']);
  if (!(preg_match('/^(\d{7})\-(\d.*)\-([A-Z]{5})$/', $form_state['values']['stanford_soe_r25_booking_attr144']))) {
      form_set_error('stanford_soe_r25_booking_attr144', t('Invalid PTA Format. The correct format is Project-Task-Award (e.g. 1234567-123-ABCDE)'));
  }
}

// Remove the Sender and other headers so emails only appear to come from Tech Training, and not the website admins.
function tt_mail_alter(&$message) {
  if (preg_match('/stanford_soe_r25/', $message['id'])) {
    unset($message['headers']['Sender']);
    unset($message['headers']['Errors-To']);
    unset($message['headers']['Return-Path']);
  }
}
